#!/usr/bin/env bash

APPNAME=$1
HOST=$2
ARCH=$3

#
APPSRC=$APPNAME
GOCOMPILER="golang/go1.24.4.${ARCH}.tar.gz"
TARGET="~/deploy"

# copy
rsync -avh --progress --delete $GOCOMPILER $HOST:"$TARGET/$APPNAME/"
rsync -avh --progress --delete $APPSRC $HOST:"$TARGET/$APPNAME/"

# exec
ssh $HOST << EOF
    set e
    cd "$TARGET/$APPNAME/"
    rm -rf go
    tar -xf "$GOCOMPILER"
    export GOROOT="$TARGET/$APPNAME/go"
    cd "$APPNAME"
    go build -o app
    ./app |& tee "$TARGET/$APPNAME/run.log"
EOF

