#!/usr/bin/env bash

APPNAME=$1
HOST=$2
ARCH=$3

#
APPSRC=$APPNAME
GOCOMPILER="go1.24.4.${ARCH}.tar.gz"
TARGET="/home/khanh/deploy"

# copy
ssh $HOST "mkdir -p \"$TARGET/$APPNAME/\""
rsync -avh --progress --delete "go_compiler/$GOCOMPILER" $HOST:"$TARGET/$APPNAME/"
rsync -avh --progress --delete $APPSRC $HOST:"$TARGET/$APPNAME/"

# exec
ssh $HOST << EOF
    set e
    export GOCOMPILER="$GOCOMPILER"
    cd "$TARGET/$APPNAME/"
    rm -rf go
    tar -xf "\$GOCOMPILER"
    export GOROOT="$TARGET/$APPNAME/go"
    export PATH="\$GOROOT/bin:\$PATH"
    cd "$APPNAME"
    go build -o app
    ./app |& tee "$TARGET/$APPNAME/run.log"
EOF

