#!/usr/bin/env bash

APPNAME=$1
HOSTLIST=$2
PRIVATEKEY=$3

# generate config
# python $APPNAME/generate_config.py $APPNAME $HOSTLIST $PRIVATEKEY

python bin/make_script.py $APPNAME $HOSTLIST $PRIVATEKEY